driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec
  
platforms:
  - name: centos-6
    driver:
      box: bento/centos-6.8

  - name: centos-7
    driver:
      box: bento/centos-7.3

  - name: debian-7
    driver:
      box: bento/debian-7.11

  - name: debian-8
    driver:
      box: bento/debian-8.6

  - name: fedora-25
    driver:
      box: bento/fedora-25

  - name: opensuse-leap
    driver:
      box: bento/opensuse-leap-42.1

  - name: ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04

  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04

suites:
  - name: create
    run_list:
      - recipe[test::create]
  - name: persist
    run_list:
      - recipe[test::persist]
  - name: remove
    run_list:
      - recipe[test::remove]
