driver:
  name: vagrant

provisioner:
  name: chef_zero
  log_level: info
  log_file: /var/log/chef-solo.log

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
  - name: opensuse-42.1
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: create
    run_list:
      - recipe[fake::create]
  - name: persist
    run_list:
      - recipe[fake::persist]
  - name: remove
    run_list:
      - recipe[fake::remove]
