<%
def opscode_box(type)
  "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_#{type}_provisionerless.box"
end
%>

driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: <%= opscode_box('ubuntu-12.04') %>

  - name: centos-6.4
    driver_config:
      box: opscode-centos-6.4
      box_url: <%= opscode_box('centos-6.4') %>

suites:
  - name: create
    run_list: ['recipe[fake::create]']
  - name: presist
    run_list: ['recipe[fake::persist]']
  - name: remove
    run_list: ['recipe[fake::remove]']
