AllCops:
  Excludes:
    - vendor/**

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
DoubleNegation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Max: 120
MethodLength:
  Max: 20
